/**
 * Finnish UI copy for the scorekeeping app (D19).
 *
 * Plain string constants — no i18n framework.
 */

export const strings = {
  appTitle: 'Scrabble-pisteet',
  homeSubtitle: 'Pidä pisteet kirjassa pöydän ääressä.',
  newGame: 'Uusi peli',
  newGameSubtitle: 'Lisää 2–4 pelaajaa ja valitse kuka aloittaa.',
  continueSection: 'Kesken olevat pelit',
  continueGame: 'Jatka',
  noInProgressGames: 'Ei kesken olevia pelejä. Aloita uusi peli.',
  historySection: 'Päättyneet pelit',
  openFinishedGame: 'Avaa',
  noFinishedGames: 'Ei päättyneitä pelejä.',
  deleteGame: 'Poista peli',
  deleteConfirmPrompt: 'Poistetaanko peli?',
  confirmDelete: 'Poista',
  deleteFailed: 'Pelin poisto epäonnistui. Yritä uudelleen.',
  turnsCount: (count: number) =>
    count === 1 ? '1 vuoro' : `${count} vuoroa`,
  back: 'Takaisin',
  menuLabel: 'Valikko',
  closeMenu: 'Sulje',
  gameMenuTitle: 'Valikko',
  noTurnsYet: 'Ei vuoroja vielä.',
  turnsFinishedHint:
    'Päättyneen pelin vuoroja ei voi muokata ennen avaamista.',
  gameNotFound: 'Peliä ei löytynyt.',
  standingsHeading: 'Tilanne',
  rankLabel: (rank: number) => `${rank}.`,
  pointsLabel: (total: number) => `${total} p`,
  whoseTurn: 'Kenen pisteet?',
  whoseTurnHint: 'Ehdotettu pelaaja on merkitty; voit kirjata myös toisen.',
  suggestedBadge: 'Ehdotettu',
  scoreLabel: 'Pisteet',
  scoreEmpty: '—',
  scoreHint: 'Kokonaisluku. Nolla = vuoro ohi.',
  keypadLabel: 'Pistenäppäimistö',
  keypadToggleSign: 'Vaihda etumerkki',
  keypadBackspace: 'Poista numero',
  keypadClearHint: 'Pidä ⌫ pohjassa tyhjentääksesi.',
  wordLabel: 'Sana (valinnainen)',
  wordPlaceholder: 'esim. kissa',
  recordTurn: 'Tallenna vuoro',
  passTurn: 'Vuoro ohi (0)',
  scoreRequired: 'Anna pisteet kokonaislukuna.',
  recordTurnFailed: 'Vuoron tallennus epäonnistui. Yritä uudelleen.',
  gameFinishedReadOnly:
    'Peli on päättynyt. Pisteitä ei voi kirjata ennen kuin avaat pelin uudelleen valikosta.',
  gameFinishedSubtitle: 'Päättynyt',
  finishGame: 'Lopeta peli',
  finishConfirmPrompt: 'Lopetetaanko peli?',
  confirmFinish: 'Lopeta',
  reopenGame: 'Avaa peli uudelleen',
  finishFailed: 'Pelin lopetus epäonnistui. Yritä uudelleen.',
  reopenFailed: 'Pelin avaaminen epäonnistui. Yritä uudelleen.',
  turnsHeading: 'Vuorot',
  lastTurnBadge: 'Viimeisin',
  noWordLabel: '—',
  undoLast: 'Kumoa viimeisin',
  undoConfirmPrompt: 'Kumoa viimeisin vuoro?',
  confirmUndo: 'Kumoa',
  cancel: 'Peruuta',
  editPlayerLabel: 'Pelaaja',
  saveEdit: 'Tallenna muutos',
  undoFailed: 'Kumoaminen epäonnistui. Yritä uudelleen.',
  editFailed: 'Muokkaus epäonnistui. Yritä uudelleen.',
  playerNameLabel: (n: number) => `Pelaaja ${n}`,
  addPlayer: 'Lisää pelaaja',
  removePlayer: 'Poista',
  nameSuggestions: 'Ehdotukset aiemmista peleistä',
  whoStarts: 'Kuka aloittaa?',
  whoStartsHint: 'Valitse kirjaimen noston voittaja.',
  startGame: 'Aloita peli',
  newGameTooFewPlayers: 'Lisää vähintään kaksi pelaajaa.',
  newGameTooManyPlayers: 'Pelaajia voi olla enintään neljä.',
  newGameDuplicateNames: 'Pelaajien nimien on oltava erilaisia.',
  newGamePickStarter: 'Valitse kuka aloittaa.',
  newGameCreateFailed: 'Pelin luonti epäonnistui. Tarkista nimet ja yritä uudelleen.',
} as const
