/**
 * Finnish UI copy for the scorekeeping app (D19).
 *
 * Plain string constants — no i18n framework.
 */

export const strings = {
  appTitle: 'Scrabble-pisteet',
  homeSubtitle: 'Pidä pisteet kirjassa pöydän ääressä.',
  newGame: 'Uusi peli',
  newGameSubtitle: 'Lisää 2–4 pelaajaa ja valitse kuka aloittaa.',
  continueSection: 'Kesken olevat pelit',
  continueGame: 'Jatka',
  noInProgressGames: 'Ei kesken olevia pelejä. Aloita uusi peli.',
  turnsCount: (count: number) =>
    count === 1 ? '1 vuoro' : `${count} vuoroa`,
  back: 'Takaisin',
  gameNotFound: 'Peliä ei löytynyt.',
  standingsHeading: 'Tilanne',
  rankLabel: (rank: number) => `${rank}.`,
  pointsLabel: (total: number) => `${total} p`,
  whoseTurn: 'Kenen pisteet?',
  whoseTurnHint: 'Ehdotettu pelaaja on merkitty; voit kirjata myös toisen.',
  suggestedBadge: 'Ehdotettu',
  scoreLabel: 'Pisteet',
  scoreHint: 'Kokonaisluku. Nolla = vuoro ohi.',
  wordLabel: 'Sana (valinnainen)',
  wordPlaceholder: 'esim. kissa',
  recordTurn: 'Tallenna vuoro',
  passTurn: 'Vuoro ohi (0)',
  scoreRequired: 'Anna pisteet kokonaislukuna.',
  scoreNotInteger: 'Pisteiden on oltava kokonaisluku.',
  scoreOutOfRange: 'Pisteet ovat liian suuret. Tarkista kirjoitusvirhe.',
  recordTurnFailed: 'Vuoron tallennus epäonnistui. Yritä uudelleen.',
  gameFinishedReadOnly: 'Peli on päättynyt. Pisteitä ei voi kirjata.',
  turnsHeading: 'Vuorot',
  lastTurnBadge: 'Viimeisin',
  noWordLabel: '—',
  undoLast: 'Kumoa viimeisin',
  undoConfirmPrompt: 'Kumota viimeisin vuoro?',
  confirmUndo: 'Kumoa',
  cancel: 'Peruuta',
  editPlayerLabel: 'Pelaaja',
  saveEdit: 'Tallenna muutos',
  undoFailed: 'Kumoaminen epäonnistui. Yritä uudelleen.',
  editFailed: 'Muokkaus epäonnistui. Yritä uudelleen.',
  playerNameLabel: (n: number) => `Pelaaja ${n}`,
  addPlayer: 'Lisää pelaaja',
  removePlayer: 'Poista',
  nameSuggestions: 'Ehdotukset aiemmista peleistä',
  whoStarts: 'Kuka aloittaa?',
  whoStartsHint: 'Valitse kirjaimen noston voittaja.',
  startGame: 'Aloita peli',
  newGameTooFewPlayers: 'Lisää vähintään kaksi pelaajaa.',
  newGameTooManyPlayers: 'Pelaajia voi olla enintään neljä.',
  newGameDuplicateNames: 'Pelaajien nimien on oltava erilaisia.',
  newGamePickStarter: 'Valitse kuka aloittaa.',
  newGameCreateFailed: 'Pelin luonti epäonnistui. Tarkista nimet ja yritä uudelleen.',
} as const
